# Generated by Django 2.2.6 on 2020-02-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200212_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.svg', upload_to='profile_pics/<django.db.models.fields.related.OneToOneField>'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
