# Generated by Django 2.2.11 on 2020-03-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_profile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='kdratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wlratio',
            field=models.IntegerField(default=0),
        ),
    ]
